name: Publish Github pages
on:
  push:
    branches:
      - master 
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Ubuntu dependencies
        run: sudo apt-get install graphviz pandoc

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          python-version: 3.12
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv

      - name: Install dependencies with river
        run: poetry install --no-interaction
        shell: bash

      - name: Build docs
        run: |
          cd benchmarks
          poetry run python render.py
          cd ..
          poetry run mkdocs build

      - name: Deploy docs
        run: |
          poetry run mkdocs gh-deploy --force
